apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
    labels:
        argocd.argoproj.io/instance: {{ .cluster.name }}-external-secrets
    name: "{{ .cluster.name }}-{{ .cluster.stage }}"
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.eu/api
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: external-secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caProvider:
        key: ca.crt
        name: bitwarden-tls-certs
        namespace: external-secrets
        type: Secret
      identityURL: https://vault.bitwarden.eu/identity
      organizationID: b1ca918d-759b-4e1e-b273-b4150163d2b2
      projectID: 9a463dec-1c0d-4f82-bd8f-b4150164a540

